services:
  lavue_app:
    image: webdevops/php-nginx-dev:8.3-alpine
    container_name: lavue_app
    environment:
      - PHP_DISPLAY_ERRORS=1
      - PHP_DATE_TIMEZONE=Asia/Ho_Chi_Minh
      - WEB_DOCUMENT_ROOT=/app/public
    networks:
      - docker-net
    volumes:
      - ".:/app"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lavue_app.rule=Host(`lavue-app.spa`)"
      - "traefik.http.routers.lavue_app.entrypoints=web"
      - "traefik.http.services.lavue_app.loadbalancer.server.port=80"
networks:
  docker-net:
